[package]
name = "dm"
version = "0.1.0"
authors = ["William Wallace <me@wiox.me>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.4.1"
detour = "0.7.1"
msgbox = "0.4.0"
sigscan = { path = "../sigscan" }
