[package]
name = "debug_server"
version = "0.1.0"
authors = ["William Wallace <me@wiox.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"

[dependencies]
dm = { path = "../dm" }
sigscan = { path = "../sigscan" }

[dependencies.detour]
version = "0.7"
default-features = false
