[package]
name = "dm-impl"
version = "0.1.0"
authors = ["Aspen <luxx4x@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
hex = "0.4"
